install: skip
language: java
jdk: openjdk11
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
services:
  - docker
before_script:
  - openssl aes-256-cbc -K $encrypted_3ea9ffab9517_key -iv $encrypted_3ea9ffab9517_iv
  - in .travis/travis_rsa.enc -out .travis/travis_rsa -d
script:
  - "./gradlew clean build"
after_script:
  - bash scripts/push-docker-image.sh
