install: skip
language: java
jdk: openjdk11
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
services:
  - docker
script:
  - ./gradlew clean build
deploy:
  - provider: script
    script: bash scripts/build-and-deploy-docker-image.sh
    skip_cleanup: true