install: skip
language: java
jdk: openjdk11
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
services:
  - docker
script:
  - ./gradlew clean build
after_script:
  - echo "Building and pushing dowell.dev to docker hub..."
  - echo "'$DOCKER_PASSWORD'" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t dowell.dev .
  - docker tag dowell.dev lukedowell/dowell.dev:$RELEASE_TAG
  - docker push lukedowell/dowell.dev:$RELEASE_TAG
  - echo "Finished pushing dowell.dev to docker hub ^_^"